reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy do
    resources :posts, only: :create
  end
  resources :posts, except: :create do
    resources :comments
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  
  resources :comments, only: [:create, :show] do
    member do
      post 'downvote'
      post 'upvote'
    end
  end
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  
  belongs_to :author,
  foreign_key: :author_id,
  class_name: :User
  
  has_many :post_subs,
  foreign_key: :post_id,
  class_name: :PostSub,
  dependent: :destroy
  
  has_many :subs,
  through: :post_subs,
  source: :sub,
  dependent: :destroy
  
  has_many :comments
  
  has_many :votes, 
  as: :votable,
  class_name: :Vote
  
  def total_votes
    sum = 0
    self.votes.each do |vote|
      sum += vote.value
    end
    sum
  end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_user
  
  def show
    @post = Post.find(params[:id])
    @all_comments = @post.comments.includes(:author)
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def upvote
    @post = Post.find(params[:id])
    vote = Vote.create!(user_id: current_user.id, votable_id: @post.id, value: 1)
    redirect_to @post
  end
  
  def downvote
    @post = Post.find(params[:id])
    vote = Vote.create!(user_id: current_user.id, votable_id: @post.id, value: -1)
    redirect_to @post
  end
  
  def update
    @post = current_user.posts.find(params[:id])
    if @post
      if @post.update(post_params)
        redirect_to post_url(@post)
      else
        flash.now[:errors] = @post.errors.full_messages
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.author_id = current_user.id
      @post.destroy
      redirect_to sub_url(@post.sub_id)
    else
      redirect_to sub_url(@post.sub_id)
    end
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      params[:post][:sub_ids].each do |sub_id|
        PostSub.create!(post_id: @post.id, sub_id: sub_id)
      end
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render 'new'
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids)
  end
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

reddit_clone/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

reddit_clone/app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% Sub.all.each do |sub| %>
    <%= sub.title %><input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" 
      <%= "checked" if @post.sub_ids.include?(sub.id) %>><br>
  <% end %>
  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label><br>
  
  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label><br>
  
  <label>Body
    <textarea name="post[content]">
    <%= @post.content %></textarea>
  </label><br>
  
  <input type="submit" value="Edit Post">
</form>

reddit_clone/app/views/posts/new.html.erb
<h1>Create Post</h1>

<form action="<%= sub_posts_url(params[:sub_id]) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% Sub.all.each do |sub| %>
    <%= sub.title %><input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><br>
  <% end %>
  <label>Title
    <input type="text" name="post[title]" value="">
  </label><br>
  
  <label>URL
    <input type="text" name="post[url]" value="">
  </label><br>
  
  <label>Body
    <textarea name="post[body]"></textarea>
  </label><br>
  
  <input type="submit" value="Create Post">
</form>

reddit_clone/app/views/posts/show.html.erb
<h1>Post Title <br><%= @post.title %></h1>
Post URL: <%= @post.url%> <br>
<h3><%= @post.content %></h3>
Written By: <%= @post.author.username %>
<br><br>
Associated Subs <br><br>
<% @post.subs.each do |sub| %>
<%= link_to sub.title, sub %> <br>
<% end %>

<form class="" action="<%= post_comments_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="content">
    <textarea name="comment[content]"></textarea><br>
  </label>
  <input type="submit" name="" value="Add Comment">
</form>
<h2> Upvote or Downvote </h2>
<%= button_to 'Upvote', upvote_post_url(@post), method: :post %>
<%= button_to 'Downvote', downvote_post_url(@post), method: :post %>
Total Votes: <%= @post.total_votes %><br>
<h2>Comments</h2>
<% @all_comments.each do |comment| %> 
  <% if comment.parent_comment_id == nil %>
    <hr>
    <%= comment.content %><br>
    Written by: <%= comment.author.username %><br>
    <% @all_comments.each do |child_comment| %>
      <% if comment.id == child_comment.parent_comment_id %>
        <div class="" style="margin-left: 30px;">
          <%= child_comment.content %><br>
          Written by: <%= child_comment.author.username %><br><br>
        </div>
      <% end %>
    <% end %>
    <form class="" action="<%= post_comments_url(@post) %>" method="post">
      <input type="hidden" name="parent_comment_id" value="<%= comment.id %>">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <label for="content">
        <textarea name="comment[content]"></textarea><br>
      </label>
      <input type="submit" name="" value="Add Child Comment">
    </form>
  <% end %>
<% end %>

<br><br>

reddit_clone/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>