reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy do
    resources :posts, only: :create
  end
  resources :posts, except: :create do
    resources :comments
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  
  resources :comments, only: [:create, :show] do
    member do
      post 'downvote'
      post 'upvote'
    end
  end
end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true
  
  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: :User
  
  has_many :post_subs,
  foreign_key: :post_id,
  class_name: :PostSub,
  dependent: :destroy
  
  has_many :posts,
  through: :post_subs,
  source: :post,
  dependent: :destroy
  
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_user
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render 'new'
    end
  end

  def index
    @subs = Sub.all
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render 'edit'
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end
  
  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

reddit_clone/app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

reddit_clone/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

reddit_clone/app/views/subs/index.html.erb
<h1>Subs#index</h1>

<% @subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub) %> <br>
<% end %>

reddit_clone/app/views/subs/new.html.erb
<h1>Create Sub</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="sub[title]" value="">
  </label><br>
  
  <label>Description
    <input type="text" name="sub[description]" value="">
  </label><br>
  
  <input type="submit" value="Create Sub">
</form>

reddit_clone/app/views/subs/show.html.erb
<h1>Subs#show</h1>
<%= @sub.title %> <br>
<%= @sub.description %> <br>
<% if @sub.moderator_id == current_user.id %>
<%= link_to 'Edit Sub', edit_sub_url(@sub) %>
<% end %><br>

<%= button_to 'Create Post', new_post_url, method: :get, params: { sub_id: @sub.id } %>

<h2>Posts</h2>
<% @sub.posts.each do |post| %>
  <%= link_to post.title, post_url(post) %><br>
<% end %>

reddit_clone/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>