reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: :destroy do
    resources :posts, only: :create
  end
  resources :posts, except: :create do
    resources :comments
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  
  resources :comments, only: [:create, :show] do
    member do
      post 'downvote'
      post 'upvote'
    end
  end
end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  has_many :moderated_subs,
  foreign_key: :moderator_id,
  class_name: :Sub,
  dependent: :destroy

  has_many :posts,
  foreign_key: :author_id,
  class_name: :Post,
  dependent: :destroy
  
  attr_reader :password
  after_initialize :ensure_session_token
  
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end
  
  private
  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to new_user_url
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

reddit_clone/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

reddit_clone/app/views/users/new.html.erb
<div class="sign-in">
  <%= image_tag('reddit.png', height: '50', width: '50') %>
  <h1 class="sign-in-title">Sign Up</h1>

  <form class="sign-in-form" action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    
    <label>Username
      <input type="text" name="user[username]" value="">
    </label><br>
    
    <label>Password
      <input type="password" name="user[password]" value="">
    </label><br>
    
    <input type="submit" value="Sign Up">
  </form>
</div>